### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by ocadaruma** [ocadaruma/tlaplus-intellij-plugin#1]

**Comment by ocadaruma** [comment]
errors:
```
TLC threw an unexpected exception. This was probably caused by an error in the spec or model. See the User Output or TLC Console for clues to what happened. The exception was a java.lang.RuntimeException : Attempted to select nonexistent field "ba" from the record [type |-> "phase2a", ins |-> r1, bal |-> 1, val |-> "aborted"] line 246, col 40 to line 246, col 43 of module PaxosCommit

The error occurred when TLC was evaluating the nested expressions at the following positions: 0. Line 244, column 3 to line 252, column 22 in PaxosCommit 1. Line 244, column 6 to line 251, column 46 in PaxosCommit 2. Line 245, column 8 to line 251, column 46 in PaxosCommit 3. Line 245, column 11 to line 245, column 28 in PaxosCommit 4. Line 246, column 11 to line 246, column 43 in PaxosCommit 5. Line 246, column 40 to line 246, column 43 in PaxosCommit
```

file: https://gist.github.com/ocadaruma/676b3b093e45f9c3ef00a00d0d955d50#file-paxoscommit-tla

exception:
```
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy20.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:220)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:63)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:100)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:64)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:52)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:156)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:206)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:190)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:102)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:68)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:158)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.AssertionError: Input <PCNext line 254, col 1 to line 254, col 6 of module PaxosCommit (255 20 258 38)>: 0:0
 must match to the pattern <(\w+) line (\d+), col (\d+) to line (\d+), col (\d+) of module (\w+)>: (\d+):(\d+)
	at com.mayreh.intellij.plugin.tlaplus.run.parsing.TLCEventParser.mustMatch(TLCEventParser.java:262)
	at com.mayreh.intellij.plugin.tlaplus.run.parsing.TLCEventParser$CoverageItemParser.parse(TLCEventParser.java:242)
	at com.mayreh.intellij.plugin.tlaplus.run.parsing.TLCEventParser$Default.lambda$addLine$6(TLCEventParser.java:128)
	at com.mayreh.intellij.plugin.tlaplus.run.parsing.TLCEventParser$MultilineTextParser.finish(TLCEventParser.java:193)
	at com.mayreh.intellij.plugin.tlaplus.run.parsing.TLCEventParser$StatefulParser.addLine(TLCEventParser.java:164)
	at com.mayreh.intellij.plugin.tlaplus.run.ui.TLCOutputConsoleView$State$Running$1.onTextAvailable(TLCOutputConsoleView.java:70)
	... 27 more
```

**Comment by ocadaruma** [comment]
Run tla file without cfg:
```
TLC threw an unexpected exception. This was probably caused by an error in the spec or model. See the User Output or TLC Console for clues to what happened. The exception was a tlc2.tool.ConfigFileException : @!@!@STARTMSG 5001:0 @!@!@ TLC encountered the following error when trying to read the configuration file TCommit.cfg: File not found.
--



```

**Comment by ocadaruma** [comment]
Copy to clipboard from TLCResultPanel's table generate <html>

**Comment by ocadaruma** [comment]
All described issues are solved now.
